# Lab 2.2: Introduction to Pandas


**University of Engineering and Technology Peshawar, Nowshera Campus**

**Course:** Machine Learning Lab

**Student Name:** Zohaib Ahmed 
**Registration Number:** 22jzele0481


---

## Table of Contents

1. [Introduction to Pandas](#1-introduction-to-pandas)  
2. [Installation](#2-installation)  
3. [Import Pandas](#3-import-pandas)  
4. [Creating DataFrame](#4-creating-dataframe)  
5. [Saving to CSV](#5-saving-to-csv)  
6. [Reading CSV Files](#6-reading-csv-files)  
7. [Basic Operations](#7-basic-operations)  
8. [DataFrame Methods](#8-dataframe-methods)

## 1. Introduction to Pandas

Here, we are learning data analysis. Pandas is a software library written for the Python programming language that helps with data manipulation and analysis. It offers various data structures which help in the manipulation of data. <br>
One of the data structures used is DataFrame.<br>
DataFrame is used as a way to store data in a rectangular grid.<br>
Similar to how data is stored in Microsoft Excel.

## 2. Installation

We can easily install this library using the terminal. Follow the steps given below to install Pandas:<br>
Step 1: Go to the Windows PowerShell.<br>
Step 2: We can install pandas with the help of pip easily. Head over to the directory where you want to install the pandas and fire the below command:<br>
__pip install pandas__<br>
This is very simple to install.

## 3. Import Pandas

In [1]:
import pandas as pd

## 4. Creating DataFrame

In [2]:
students = {
    'Name': ["Zohaib Ahmed ", " Ibraheem khan", "Muhammad Abid", "Shumail Khan","Qasim Ali"],
    'Marks': [80, 72, 77, 65, 15],
    'Class':["1st Year", "2nd Year", "1st Year", "3rd Year", "2nd Year"],
    'Age': [20, 21, 19, 22, 21]
}

In [3]:
df = pd.DataFrame(students)

In [4]:
df

             Name  Marks     Class  Age
0   Zohaib Ahmed      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

## 5. Saving to CSV

In [5]:
df.to_csv('pythonMonday.csv')

In [6]:
df.to_csv('pythonMondayRemoveIndex.csv', index=False)

## 6. Reading CSV Files

In [7]:
classData = pd.read_csv("pythonMondayRemoveIndex.csv")
classData

             Name  Marks     Class  Age
0   Zohaib Ahmed      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

## 7. Basic Operations

In [8]:
df.head()

             Name  Marks     Class  Age
0   Zohaib Ahmed      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [9]:
df.head(3)

             Name  Marks     Class  Age
0   Zohaib Ahmed      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19

In [10]:
df.tail(3)

            Name  Marks     Class  Age
2  Muhammad Abid     77  1st Year   19
3   Shumail Khan     65  3rd Year   22
4      Qasim Ali     15  2nd Year   21

In [11]:
df.describe()

           Marks        Age
count   5.000000   5.000000
mean   61.800000  20.600000
std    26.771253   1.140175
min    15.000000  19.000000
25%    65.000000  20.000000
50%    72.000000  21.000000
75%    77.000000  21.000000
max    80.000000  22.000000

## 8. DataFrame Methods

In [12]:
df['Name']

0     Zohaib Ahmed
1     Ibraheem khan
2     Muhammad Abid
3      Shumail Khan
4         Qasim Ali
Name: Name, dtype: object

In [13]:
type(df['Name'])

pandas.core.series.Series

In [14]:
df['Age'][0]

20

In [15]:
df.rename(columns={'Age': 'AGE'})

             Name  Marks     Class  AGE
0   Zohaib Ahmed      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [16]:
df.index = ["First","Second", "Third", "Fourth", "Fifth"]
df

                  Name  Marks     Class  Age
First    Zohaib Ahmed      80  1st Year   20
Second   Ibraheem khan     72  2nd Year   21
Third    Muhammad Abid     77  1st Year   19
Fourth    Shumail Khan     65  3rd Year   22
Fifth        Qasim Ali     15  2nd Year   21

In [18]:
df.drop(['Age'], axis=1)

                  Name  Marks     Class
First    Zohaib Ahmed      80  1st Year
Second   Ibraheem khan     72  2nd Year
Third    Muhammad Abid     77  1st Year
Fourth    Shumail Khan     65  3rd Year
Fifth        Qasim Ali     15  2nd Year

In [19]:
df.reset_index(drop=True)

             Name  Marks     Class  Age
0   Zohaib Ahmed      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21